### ISSUE TITLE
Options Page Pre-Authentication

### ISSUE THREAD

**Issue by kbaileyky** [privly/privly-chrome#82]
When not logged into to Privly, if the Options page is selected from the drop down menu, the user will be taken to the options page as though they have already logged in. The nav bar at the top will give the user the options: history, new link, options, and log out. 

Other pages from the drop down menu only show the option to log in on the nav bar and display a message asking users to sign in.

**Comment by irdan** [comment]
@kbaileyky The options page contains a setting to specify your content server.  I believe requiring auth was removed from that page so that the content server could be changed without logging in.  This avoids preventing someone from configuring their content if they don't have an account on the default content server.

While that is a reasonable change, the UI should not convey to the user that they are logged in when they are not.

Even though you experienced this while using the chrome version, I imagine this UI issue would manifest in firefox as well.  As such, this issue should be addressed in the privly-applications repo.  If you or someone else wants to resolve it the relevant files are in `privly-applications/Pages`.

**Comment by smcgregor** [comment]
@kbaileyky Could you include a screen capture? I am having trouble replicating the issue. @irdan is correct that this is better placed in the https://github.com/privly/privly-applications repo. You can discuss the issue here or close this issue and reference it from a new issue on privly-applications.


![screen shot 2015-02-09 at 12 01 26 pm](https://cloud.githubusercontent.com/assets/64780/6114498/6dd590ba-b053-11e4-8ad1-9fea9fe1bc75.png)
.

**Comment by kbaileyky** [comment]
Moved to https://github.com/privly/privly-applications/issues/148.
